### ISSUE TITLE
Webdemo is broken

### ISSUE THREAD

**Issue by phuhl** [triska/rits#3]
When visiting `https://www.metalevel.at/rits/demo` i get

      Internal server error
      
      goal unexpectedly failed: server:http_reply_from_files('.',[],[path_info(demo),protocol(http),peer(ip(127,0,0,1)),pool(client('httpd@4040',http_unix_daemon:http_dispatch,<stream>(0xe4d4f0),<stream>(0xf8b470))),input(<stream>(0xe4d4f0)),method(get),request_uri('/demo'),path('/demo'),http_version(1-1),host(localhost),port(4040),user_agent('SWI-Prolog'),connection(close)])
      
      SWI-Prolog httpd at localhost.localdomain

**Comment by triska** [comment]
Thank you very much for reporting this! The correct link is:

https://www.metalevel.at/rits/demo.html

The reason you got to the wrong location was a broken HTTP&rightarrow;HTTPS redirect.

I have taken the following steps to mitigate this issue:

1. I have corrected the redirect, so that you are correctly taken to `demo.html` instead of `demo` when you use the HTTP&nbsp;link.
2. I have changed the link in the `README` to directly point to the HTTPS version, so that the redirect is in fact no longer&nbsp;needed at&nbsp;all if you access&nbsp;RITS from this repository.

The reason I did not notice this problem is that I already had an HSTS setting for `metalevel.at`, and so my browser redirected internally to the HTTPS version of `demo.html`.

Please let me know whether it now works for you. Enjoy!

**Comment by phuhl** [comment]
Works beautifully.

**Comment by triska** [comment]
Thank you!
